dist: trusty
sudo: false
language: go
go:
  - 1.12.x

env:
  - GO111MODULE=on

services: mongodb

script:
  - go build 
  - go test -v

install:
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=master bash)"

jobs:
  include:
    - stage: build
      if: type = pull_request
      before_install: skip
      script: go build -v
    - stage: test
      if: type = pull_request
      before_install: skip
      script: go test -v

