dist: trusty
language: go
go:
  - 1.12.x

env:
  - GO111MODULE=on

install:
  - export GOPATH=$HOME/gopath/src/github.com/amorist/mango
  - cd src/github.com/amorist/mango && go install && go test && cd -

script: go get github.com/amorist/mango && go test -v

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      if: type = push
      language: node_js
      node_js: lts/*
      before_install: skip
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: install
      deploy:
        provider: script
        skip_cleanup: true
        script: >-
          npm install @semantic-release/changelog -D &&
          npm install @semantic-release/exec -D &&
          npm install @semantic-release/git -D &&
          npx semantic-release
