dist: trusty
sudo: false
language: go
go:
  - 1.12.x

env:
  - GO111MODULE=on

script: go get -t -v ./...

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      if: type = push
      language: node_js
      node_js: lts/*
      before_install: skip
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: go get -t -v ./...
      deploy:
        provider: script
        skip_cleanup: true
        script: >-
          npm install @semantic-release/changelog -D &&
          npm install @semantic-release/exec -D &&
          npm install @semantic-release/git -D &&
          npx semantic-release
